steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['package']

  - name: gcr.io/cloud-builders/docker
    #args: ['build', '-f', 'src/main/docker/Dockerfile.jvm', '-t', 'gcr.io/$PROJECT_ID/cheese-quizz-client:latest', '--build-arg=JAR_FILE=target/quizz-client-1.0.0-SNAPSHOT-runner.jar', '.']
    args: ['build', '-f', 'src/main/docker/Dockerfile.jvm', '-t', 'europe-docker.pkg.dev/$PROJECT_ID/container-registry/cheese-quizz-client:latest', '--build-arg=JAR_FILE=target/quizz-client-1.0.0-SNAPSHOT-runner.jar', '.']
    
#images: ['gcr.io/$PROJECT_ID/cheese-quizz-client:latest']
images: ['europe-docker.pkg.dev/$PROJECT_ID/container-registry/cheese-quizz-client:latest']